version: '3.7'

services:

  otherdb:
    image: library/postgres:9.6.17-alpine
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_DB=openfire"
      - "POSTGRES_USER=openfire"
      - "POSTGRES_PASSWORD=hunter2"
    volumes:
      - ./sql/otherdomain:/docker-entrypoint-initdb.d
    networks:
      openfire-clustered-net:
        ipv4_address: 172.60.0.111
  
  otherxmpp:
    image: "openfire:${OPENFIRE_TAG}"
    ports:
      - "5229:5222"
      - "5269:5269"
      - "7079:7070"
      - "7449:7443"
      - "9099:9090"
    depends_on:
      - "otherdb"
    volumes:
      - ./_data/xmpp/otherdomain/conf:/var/lib/openfire/conf
      #- ./_data/plugins:/opt/plugins
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "-s", "otherdb:5432", "--", "/sbin/entrypoint.sh"]
    networks:
      openfire-clustered-net:
        ipv4_address: 172.60.0.110
    extra_hosts:
      - "xmpp.localhost.example:172.60.0.10"
      - "xmpp.localhost.example:172.60.0.20"
      - "xmpp.localhost.example:172.60.0.30"
      - "conference.xmpp.localhost.example:172.60.0.10"
      - "conference.xmpp.localhost.example:172.60.0.20"
      - "conference.xmpp3.localhost.example:172.60.0.30"
      - "otherxmpp.localhost.example:172.60.0.110"
      - "conference.otherxmpp.localhost.example:172.60.0.110"
  
  xmpp1:
    extra_hosts: 
      - "otherxmpp.localhost.example:172.60.0.110"
      - "conference.otherxmpp.localhost.example:172.60.0.110"

  xmpp2:
    extra_hosts: 
      - "otherxmpp.localhost.example:172.60.0.110"
      - "conference.otherxmpp.localhost.example:172.60.0.110"
  
  xmpp3:
    extra_hosts: 
      - "otherxmpp.localhost.example:172.60.0.110"
      - "conference.otherxmpp.localhost.example:172.60.0.110"
